import re

from forum.models import User, db

# -------------------------
# Regex Validation Rules
# -------------------------

password_regex = re.compile(r"^[a-zA-Z0-9!@#%&]{6,40}$")
username_regex = re.compile(r"^[a-zA-Z0-9!@#%&]{4,40}$")
email_regex = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


# -------------------------
# Validation Functions
# -------------------------

def valid_username(username):
    return bool(username_regex.match(username))


def valid_password(password):
    return bool(password_regex.match(password))


def valid_email(email):
    return bool(email_regex.match(email))


# -------------------------
# Account Creation
# -------------------------

def register_user(username, password, email, privacy="public"):
    """Create and persist a new user account."""
    if not valid_username(username):
        return "Invalid username"

    if not valid_password(password):
        return "Invalid password"

    if not valid_email(email):
        return "Invalid email"

    if privacy not in ["public", "private"]:
        return "Invalid privacy setting"

    # Check if username or email already exist
    existing_user = User.query.filter_by(username=username).first()
    if existing_user:
        return "Username already taken"
    
    existing_email = User.query.filter_by(email=email).first()
    if existing_email:
        return "Email already registered"

    # Create user object (id is auto-generated by the database).
    new_user = User(
        email=email,
        username=username,
        password=password,
        privacy=privacy,
    )

    # Add default permissions
    new_user.add_permission("post:create")
    new_user.add_permission("comment:create")

    # Save to database
    db.session.add(new_user)
    db.session.commit()

    return new_user